output "id" {
  value = aws_instance.web.id
}

output "ami" {
  value = aws_instance.web.ami
}

output "arn" {
  value = aws_instance.web.arn
}

output "public-dns" {
  value = aws_instance.web.public_dns
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = var.key_name
}